        databases:
  - name: BudgetApp
    databaseName: budget_q473
    user: budget_q473_user
    plan: free
services:
  - type: web
    name: BudgetApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: BudgetApp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free