default: &default
  adapter: postgresql
  username: postgres
  password: Aubin@2106
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: budget_app_development

test:
  <<: *default
  database: budge_app_test

production:
  <<: *default
  database: budget_app_production
  

  
